name: my_chat_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.5
  firebase_core: ^1.10.6
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  firebase_storage: ^10.2.5
  firebase_messaging: ^11.2.6
  uuid: ^3.0.5
  path_provider: ^2.0.8
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
